### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by Rookie-Farmer** [PCJones/Ultimate-Splinterlands-Bot-V2#1]
When an Incorrect password is used, the system still says "Login Successful" but then the user name cannot be pulled from API, nor can the ERC resulting in the account not being used.

**Comment by PCJones** [comment]
Fixed with https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/commit/90f13c4b98c1453fd6892603c9a6ff782628c7e7
