### ISSUE TITLE
 invalid access token 

### ISSUE THREAD

**Issue by mamasexeno** [PCJones/Ultimate-Splinterlands-Bot-V2#104]
error invalid access token for user. at CheckEnemyHasPickedAsyn in system nullRefenrenceExcepton
how fix that?

**Comment by PCJones** [comment]
Sorry for the slow response, is it fixed now?

**Comment by mamasexeno** [comment]
still the same error

**Comment by mamasexeno** [comment]
![error](https://user-images.githubusercontent.com/105907107/210936238-4f90d2d5-2f11-4773-aa12-667cb9cb29ce.png)

**Comment by PCJones** [comment]
Please try the newest release, this error should be fixed now:
https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases
