### ISSUE TITLE
API Error: System.Net.Http.HttpRequestException: Connection timed out (splinterlandsapi.pcjones.de:8080)

### ISSUE THREAD

**Issue by Raystorm7** [PCJones/Ultimate-Splinterlands-Bot-V2#107]
Hi,
for some time the bot no longer works and get this error. Runs on a rasperry 4. How can I solve? Thank you.
![image](https://user-images.githubusercontent.com/7420345/223637293-77622aa7-138c-4315-bddf-7856ec24a549.png)

**Comment by ElBiasto** [comment]
same error here on Windows11

**Comment by PCJones** [comment]
Hi,

this really looks like you are using an older version of the bot. Please update and it should work again. If not, please send your config.txt files
