### ISSUE TITLE
Critical Error: The HTTP request to the remote WebDriver server error

### ISSUE THREAD

**Issue by DoubleUltera** [PCJones/Ultimate-Splinterlands-Bot-V2#11]
The problem seems to be intermittent as I've been able to run the bot on the same machine. One time, a reboot fixed it as well.
The vps is running on Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-88-generic x86_64)

`root@localhost:~/sl-bot/linux-x64# ./Ultimate\ Splinterlands\ Bot\ V2
[10/1/2021 8:23:35 AM] --------------------------------------------------------------
[10/1/2021 8:23:35 AM] Ultimate Splinderlands Bot V2 by PC Jones
[10/1/2021 8:23:35 AM] Join the telegram group https://t.me/ultimatesplinterlandsbot
[10/1/2021 8:23:35 AM] Join the discord server https://discord.gg/hwSr7KNGs9
[10/1/2021 8:23:35 AM]                Close this window to stop the bot
[10/1/2021 8:23:35 AM] -------------------------------------------------------------
[10/1/2021 8:23:35 AM] Reading config...
[10/1/2021 8:23:35 AM] Config loaded!
[10/1/2021 8:23:35 AM] Config parameters:
DEBUG: True
WRITE_LOG_TO_FILE: False
PRIORITIZE_QUEST: True
CLAIM_QUEST_REWARD: False
CLAIM_SEASON_REWARD: False
REQUEST_NEW_QUEST: System.String[]
SLEEP_BETWEEN_BATTLES: 0
ECR_THRESHOLD: 60
USE_API: True
HEADLESS: True
MAX_BROWSER_INSTANCES: 1

[10/1/2021 8:23:35 AM] Reading accounts.txt...
[10/1/2021 8:23:35 AM] Loaded 1 accounts!
[10/1/2021 8:23:35 AM] Creating 1 browser instances...
Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 42993
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
ChromeDriver was started successfully.
Connection refused [fe80::250:56ff:fe0e:afea%2]:42993 (localhost:42993)
[10/1/2021 8:24:36 AM] Critical Error: The HTTP request to the remote WebDriver server for URL http://localhost:42993/session timed out after 60 seconds.
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 38083
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
Connection refused [fe80::250:56ff:fe0e:afea%2]:38083 (localhost:38083)
ChromeDriver was started successfully.
[10/1/2021 8:25:36 AM] Critical Error: The HTTP request to the remote WebDriver server for URL http://localhost:38083/session timed out after 60 seconds.
Connection refused [fe80::250:56ff:fe0e:afea%2]:46071 (localhost:46071)
Connection refused [fe80::250:56ff:fe0e:afea%2]:46071 (localhost:46071)
Connection refused [fe80::250:56ff:fe0e:afea%2]:46071 (localhost:46071)
Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 46071
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Connection refused [fe80::250:56ff:fe0e:afea%2]:4607
![Noname](https://user-images.githubusercontent.com/29980671/135548126-d4a5814a-d775-4cf8-b833-3380d33301cd.jpg)
1 (localhost:46071)
Connection refused [fe80::250:56ff:fe0e:afea%2]:46071 (localhost:46071)
ChromeDriver was started successfully.
`

**Comment by PCJones** [comment]
Can you enable CHROME_NO_SANDBOX and set it to true?

**Comment by PCJones** [comment]
Feel free to reopen if you still have this bug
