### ISSUE TITLE
Force Quest Even When ECR has reached

### ISSUE THREAD

**Issue by Kurotamashi94** [PCJones/Ultimate-Splinterlands-Bot-V2#13]
The Idea was For Example ERC Threshold Set to 70,
When the Account reaches  69%, check if quest is finish. if not, ignore threshold and continue till it is finish.

**Comment by PCJones** [comment]
This has been implemented in the newest release!
https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases/tag/v2.10
