### ISSUE TITLE
(feature request) add a parameter to prioritise keeping league position when close to season end

### ISSUE THREAD

**Issue by fabio80mi** [PCJones/Ultimate-Splinterlands-Bot-V2#19]
Hello!
This is another feature request picked up from Discord and posted here for simplicity
Imagine having a parameter like 

PrioritiseLeagueAtSeasonEnd
 which act like this

PrioritiseLeagueAtSeasonEnd= false ignore the parameter and work as usual
PrioritiseLeagueAtSeasonEnd= true
If season end more than 8 hours away ignore the parameter and work as usual
if season end is within 8 hours and your current rating > 40 than the limit of dropping to previous league work as usual (for example if you are in Silver 1 league this means if you are > 1040 rating)
if season end is within 8 hours and you are at risk of dropping to the previous league --> skip account and do not play

The intended behaviour here is that lets say you are at 1020 rating we want to avoid the bot playing and maybe have a losing streak and ending up at at rating of 999 by season end

**Comment by PCJones** [comment]
Will definitely come, thanks for the suggestion!
