### ISSUE TITLE
Log cleanup / changes

### ISSUE THREAD

**Issue by instruite** [PCJones/Ultimate-Splinterlands-Bot-V2#22]
Hello

Can the information about API bot be moved to say config file (as header) rather than in log, because when logging to file it just checking log bit difficult by occupying so many lines

Also the formatting for log (like colors) which display nicely on console does not help when checking log file as those as displayed as unrecognized characters and just makes values very difficult to read 

Thanks

**Comment by PCJones** [comment]
Hi, I know about the problems regarding the colors in log files, I'll try to find a solution

**Comment by PCJones** [comment]
Release 2.7 will have the following config options:
DISABLE_CONSOLE_COLORS
SHOW_API_RESPONSE
SHOW_BATTLE_RESULTS
