### ISSUE TITLE
Time when the fight begins

### ISSUE THREAD

**Issue by FoXxx87** [PCJones/Ultimate-Splinterlands-Bot-V2#27]
- Greetings! Please add to the V2 bot the time when it starts the battle, a very nice option in previous versions. Thanks!
- I also want to suggest that they do, a timer that delays the first battle, (It happens that you change some parameters in the bot's settings and restart the bot and he immediately goes into battle!)

**Comment by FoXxx87** [comment]
When we launch the bot, it immediately makes the first battle and then makes the established groove, this is sometimes not good.  You can make a setting that will postpone the first battle for a while.

**Comment by PCJones** [comment]
The bot now waits 3 seconds until it starts

**Comment by FoXxx87** [comment]
MINUTES_BATTLES_INTERVAL=55 , Bot first second battle in 55 minutes.25 minutes passed and I wanted to change the QUEST_PRIORITY parameter, I need to turn off the bot, change the QUEST_PRIORITY parameter in .env, and then start the bot, the bot will not take into account the pause that was before and start a new battle immediately, and then pause MINUTES_BATTLES_INTERVAL = 55, I want so that there would be an option responsible for the beginning of the first battle, so that the first battle could be postponed for 1 -, 2-10-15 ....... minutes. I hope I got my idea across to you. Sincerely FoXxx87/
