### ISSUE TITLE
cards, not choosi anything

### ISSUE THREAD

**Issue by Maxmp89** [PCJones/Ultimate-Splinterlands-Bot-V2#28]
every time I open the bot, it logs everything right when choosing the cards, not choosi anything.

**Comment by Maxmp89** [comment]
I've already done it doesn't always work for only the API I think the
problem is in the api

Em sáb, 23 de out de 2021 22:46, PCJones ***@***.***>
escreveu:

**Comment by PCJones** [comment]
Please try again with the newest version, it should work fine with lightning mode

**Comment by Maxmp89** [comment]
Isso funcionou!

Em qua., 17 de nov. de 2021 às 22:25, PCJones ***@***.***>
escreveu:

**Comment by Maxmp89** [comment]
That worked!

Em qua., 17 de nov. de 2021 às 22:25, PCJones ***@***.***>
escreveu:
