### ISSUE TITLE
Fall back strategy

### ISSUE THREAD

**Issue by ElBiasto** [PCJones/Ultimate-Splinterlands-Bot-V2#29]
I currently often have the problem that the API is not worink and I'm losing my battles. That's why I started to use the old V1 Bot without API. It does always enter battles but the winrate is way lower.
What I think could solve this problem would be to combine both things. If the API is not working just fall back to use the V1 code without API.

**Comment by PCJones** [comment]
Yes that is planned! But for now it seems like the API has stabilized

**Comment by PCJones** [comment]
The API has been stable for over 6 months now, so there is no need for this anymore
