### ISSUE TITLE
BotInstance.cs critical error possibly linked with some sleep timers

### ISSUE THREAD

**Issue by fabio80mi** [PCJones/Ultimate-Splinterlands-Bot-V2#33]
I get this quite frequently on 2.3.2b on Linux
From the code it seems something related to some sleep function?

![image](https://user-images.githubusercontent.com/89753279/138822110-ac133c74-e072-4bd0-ba42-68aecd565765.png)

**Comment by PCJones** [comment]
Can you send your config?

**Comment by fabio80mi** [comment]
Absolutely!
I did notice this on Linu
x (Ubuntu) VM. in multiple of them. 
Again this is an intermittent issue it happens maybe once every 20 battle

Attached my config file with private api activated
[config.txt](https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/files/7456262/config.txt)

**Comment by PCJones** [comment]
Are you still experiencing this issue?

**Comment by PCJones** [comment]
This will be fixed in the next release
