### ISSUE TITLE
Rating threshold to start games

### ISSUE THREAD

**Issue by AwesomeJester** [PCJones/Ultimate-Splinterlands-Bot-V2#34]
Please consider adding a stop value to start new games if the rating reaches "[...]. Would make a lot of sense towards season end to avoid that a bot gets close to being downgraded a league but nonetheless keeps starting games.

Should be close to the code used for the Capture Rate Threshold and the rating is pulled already anyhow from the API. Would likely help save a big amount of DEC for everyone as I would assume in most cases 3 additional chests from a higher league outweight the potential gain from keeping the bot playing a (few) day(s) at season end.

**Comment by PCJones** [comment]
> 
> 
> Just noted it had potentially already been asked for in a similiar way: #19

Agree, I will keep https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/issues/19 open
