### ISSUE TITLE
Error at waiting for match details

### ISSUE THREAD

**Issue by theresthatguy** [PCJones/Ultimate-Splinterlands-Bot-V2#40]
Error: username: Error at waiting for match details: Error: no battle queue transaction found with ID [sl_acf850fe75980583e970c890d44ecacf] I am seeing this quite often. I check the account the sps website and the match went through without selecting any cards and there is temp rank ban placed on the account.

**Comment by PCJones** [comment]
Please try https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases/tag/v2.6

**Comment by PCJones** [comment]
Feel free to reopen if you still have this bug
