### ISSUE TITLE
does not recognize the chromedriver, macos

### ISSUE THREAD

**Issue by ralts00** [PCJones/Ultimate-Splinterlands-Bot-V2#42]
The official Chromedriver is stored in the correct directory but the BOT sends a message saying that it is not installed.
In the previous version of the BOT if it worked.
<img width="1109" alt="Captura de Pantalla 2021-11-17 a la(s) 8 04 24 p m" src="https://user-images.githubusercontent.com/5034252/142338105-a6a20403-3bbd-459f-bdcb-c9e05ef5ade7.png">
<img width="1109" alt="Captura de Pantalla 2021-11-17 a la(s) 8 04 38 p m" src="https://user-images.githubusercontent.com/5034252/142338109-5ba2a693-e37a-47a8-bc5a-03dd2c9c917a.png">

**Comment by PCJones** [comment]
This is a known bug that existed in the previous version too.
Just write 
touch chromedriver.exe
And it will work

**Comment by ralts00** [comment]
it works, thank you very much
