### ISSUE TITLE
suggestion: ERC level to resume account

### ISSUE THREAD

**Issue by ralts00** [PCJones/Ultimate-Splinterlands-Bot-V2#45]
It would be very useful if the robot only resumes battles from an account that has "x" ERC, otherwise it is always playing at the lowest ERC allowed by personal settings.

**Comment by poduardo** [comment]
Agree. It would be also useful an option to close the bot after ERC reached.

**Comment by royruzaini** [comment]
need this too, else it will keep play at 75% at all time

**Comment by PCJones** [comment]
The next Update will add START_BATTLE_ABOVE_ECR and STOP_BATTLE_BELOW_ECR parameters :)
