### ISSUE TITLE
empty battles in a row

### ISSUE THREAD

**Issue by ralts00** [PCJones/Ultimate-Splinterlands-Bot-V2#46]
Yesterday and today the bot has been sending BAN by not completing the battle, this is happening to me often, how can I avoid it?
<img width="1593" alt="Captura de Pantalla 2021-11-19 a la(s) 9 30 22 a m" src="https://user-images.githubusercontent.com/5034252/142648821-d446e488-88ef-4478-9573-d02f6185fde3.png">

**Comment by PCJones** [comment]
Please report if you still have this error with 2.7:
https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases

**Comment by PCJones** [comment]
Feel free to reopen if you still have this bug
