### ISSUE TITLE
Not using Rented cards

### ISSUE THREAD

**Issue by Notzky** [PCJones/Ultimate-Splinterlands-Bot-V2#52]
Hello.

I don't know if I'm doing the right thing, I'm in Diamond league and the bot keeps choosing those with level 1 summoners instead of those with higher level cards. Need help.

Thanks

**Comment by mutusfa** [comment]
Bot doesn't even use cards I own. Djinn Chwalla is superior to Cursed Windeku if both are available (and I don't need death splinter specifically).

**Comment by PCJones** [comment]
This never really was a bug, but it should be "fixed" with the new API :)
