### ISSUE TITLE
Feature Request: Ignore ERC threshold if daily quest not complete

### ISSUE THREAD

**Issue by fabio80mi** [PCJones/Ultimate-Splinterlands-Bot-V2#54]
Hello!
This is a repost of a feature request from another player in the V1 Bot

Basically if an account has not finished the daily quest yet would be great to have a parameter to have the account keep going, even lower than ECR threshold, until the daily quest is complete

**Comment by PCJones** [comment]
This has been implemented in the newest release!
https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases/tag/v2.10
