### ISSUE TITLE
Feature: prioritize splinter

### ISSUE THREAD

**Issue by charge9k** [PCJones/Ultimate-Splinterlands-Bot-V2#55]
How it would work:

A user defined setting to prioritize splinter(s) when selecting deck for each battle. For example, 

SPLINTER_PRIO=water
Bot will select water splinter if battle rules allow it. If not, select any appropriate deck.

SPLINTER_PRIO=water,fire
Bot will select water or fire if battle rules allow it.

**Comment by PCJones** [comment]
This has been added in the last update
