### ISSUE TITLE
rename the Ultimate Splinterlands Bot V2

### ISSUE THREAD

**Issue by francuzzz** [PCJones/Ultimate-Splinterlands-Bot-V2#60]
Please rename the Ultimate Splinterlands Bot V2 file without spaces, it interferes with automation. For Ansible spaces are bad. Thank you!

**Comment by PCJones** [comment]
Hi,

I agree that it's sometimes annoying, but you can easily automate stuff on e.g. linux by adding a backspace before every space, e.g.
`Ultimate\ Splinterlands\ Bot\ V2`
