### ISSUE TITLE
Error at checking for update

### ISSUE THREAD

**Issue by nicdance** [PCJones/Ultimate-Splinterlands-Bot-V2#62]
During the startup, I get this error. 

Error at checking for update: String '2022-01-28 22:54:52' was not recognized as a valid DateTime.

I have the latest Windows build  I downloaded via the link shared on discord

https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases/tag/v2.9-fix2

**Comment by PCJones** [comment]
This will be fixed in the next update, thanks
