### ISSUE TITLE
multiple alerts, can't start

### ISSUE THREAD

**Issue by ralts00** [PCJones/Ultimate-Splinterlands-Bot-V2#70]
It is the first time that I have alerts from the robot.
i'm on mac
<img width="310" alt="Captura de Pantalla 2022-03-20 a la(s) 4 57 34 p m" src="https://user-images.githubusercontent.com/5034252/159189737-33e6c993-ca92-40c9-bff0-8c6dc86853ee.png">

**Comment by PCJones** [comment]
On MacOS you need to allow all files, I'm not sure how to do it. Feel free to join the discord server, there are some people who can help
