### ISSUE TITLE
looking for new bot

### ISSUE THREAD

**Issue by nashy15973** [PCJones/Ultimate-Splinterlands-Bot-V2#84]
anyone has a new bot for splinterlands with high winning rates

**Comment by RedFox134** [comment]
This isn't really the best place to ask for help setting up/configuring the bot.  It's better to only report issues found or ask for enhancements to make the bot better.  If you're looking for help you can join the discord and I'm sure there are a few that would be willing to help with  any questions.  [https://discord.gg/hvXnyaUZ](https://discord.gg/hvXnyaUZ)
