### ISSUE TITLE
Critical Error Sneak not in Dictionary

### ISSUE THREAD

**Issue by TheEhTeam** [PCJones/Ultimate-Splinterlands-Bot-V2#92]
Has anyone had issues with this?
![SplinterlandsBotError](https://user-images.githubusercontent.com/111928670/186280791-81ea21dd-7d22-489f-a941-c193e2e8eb84.jpg)
I'm no programmer so not sure what to do with that info. Sneak does exist in the dictionary in the bot files. I tried disabling focus on quest as well.

**Comment by PCJones** [comment]
Please update the bot, this has already been fixed: https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2/releases
