### ISSUE TITLE
Rise of the Commons and Lost Legendaries fail to submit a Team is use 0 mana cards is set to true

### ISSUE THREAD

**Issue by AvalonCarnival** [PCJones/Ultimate-Splinterlands-Bot-V2#95]
Rise of the Commons is a rule set that does not allow Epics or Legendaries which would exclude any of the 5 Fiends from being played.
Lost Legendaries is a ruleset that does not allow Legendaries which would exclude any of the 5 Fiends from being played.

The presumption is an invalid Team is being submitted because a Legendary Fiend 0 mana card has been placed in the Team because use 0 mana cards is set to true.

**Comment by PCJones** [comment]
Hi,

this has been fixed on the API a few days ago. Thanks for the report!
